apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: library-monolith
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:  
  rules:
  - host: www.library.com/monolith
    http:
      paths:
      - path: /api/v1
        pathType: ImplementationSpecific
        backend:
          service:
            name: library-monolith
            port:
              name: 8080
  - host: www.library.com/microservice
    http:
      paths:
      - path: /api/v1/books
        pathType: ImplementationSpecific
        backend:
          service:
              name: library-monolith
              port:
                number: 8080
      - path: /api/v1/users/.*/comments
        pathType: ImplementationSpecific
        backend:
          service:
              name: library-monolith 
              port:
                number: 8080
      - path: /api/v1/users
        pathType: ImplementationSpecific
        backend:
          service:
              name: userms
              port:
                number: 8090
