apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: library-monolith
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:  
  rules:
  - host: library.com
    http:
      paths:
      - path: /books
        backend:
          serviceName: library-monolith
          servicePort: 8080
      - path: /users
        backend:
          serviceName: userms
          servicePort: 8090

