apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: library-monolith
  name: library-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-monolith
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library-monolith
    spec:
      containers:
      - name: library-monolith
        image: juablazmahuerta/library-monolith:0.0.1
        env:
        - name: USER-MS_URL
          value: http://userms:8090
        - name: USE_USER-MS
          value: "true"
        - name: DATABASE_HOST
          value: mysql-db
        - name: DATABASE_SCHEMA
          value: monolith_db
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASS
          value: password
        - name: DATABASE_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: library-monolith
  labels:
    app: library-monolith
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: library-monolith
  type: NodePort